In [1]:
import pandas as pd 
import datetime
import requests 
import json
from datetime import date, timedelta
import time

## 1. 일별 박스오피스 순위

###      1) 다양성 영화, 상업 영화 전부 포함

In [2]:
key = "b70da09aaa9ad76068d1154144860ac5"
date_now = date.today() - timedelta(1)
date_now = date_now.strftime('%Y%m%d')
url = 'http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key={}&targetDt={}'.format(key, date_now)

res = requests.get(url)

text = res.text
d = json.loads(text)
movie_list = []

for b in d['boxOfficeResult']['dailyBoxOfficeList']:
    movie_list.append([b['rank'], b['movieNm'], b['rankOldAndNew'], b['openDt'], 
    b['salesAmt'], b['salesAcc'], b['audiCnt'], b['audiAcc'], b['scrnCnt'], b['showCnt']])
    

daily_data = pd.DataFrame(data=movie_list, columns=['순위', '영화명', '신규진입여부', '개봉일자', '당일 매출액', '누적 매출액', '당일 관객수', '누적 관객수', '당일 상영 스크린 수', 
                                            '당일 상영 횟수'])

In [3]:
# 당일(하루 전까지만 가능) 박스오피스 순위(옵션 다양: http://www.kobis.or.kr/kobisopenapi/homepg/apiservice/searchServiceInfo.do)
print('검색 날짜 : {}'.format(date_now))
daily_data

검색 날짜 : 20220711

,순위,영화명,신규진입여부,개봉일자,당일 매출액,누적 매출액,당일 관객수,누적 관객수,당일 상영 스크린 수,당일 상영 횟수
0,1,토르: 러브 앤 썬더,OLD,2022-07-06,1114714960,20344833370,102776,1867653,1728,8130
1,2,탑건: 매버릭,OLD,2022-06-22,1027163520,50931440970,100435,4754158,1220,4861
2,3,헤어질 결심,OLD,2022-06-29,429553410,9356032970,41739,927020,674,1759
3,4,범죄도시 2,OLD,2022-05-18,128659940,130334411080,12547,12601322,495,821
4,5,마녀(魔女) Part2. The Other One,OLD,2022-06-15,67594700,28662618080,6619,2779293,364,592
5,6,빅샤크4: 바다공룡 대모험,OLD,2022-07-06,13841300,405073680,1766,43888,208,221
6,7,BIFAN2022 부천 초이스: 단편 1,OLD,,6865000,35165000,1373,7033,1,8
7,8,BIFAN2022 엑스라지 4,NEW,,5635000,5635000,1127,1127,1,7
8,9,큐어,OLD,2022-07-06,10393100,132394700,1026,12468,49,83
9,10,더 킬러: 죽어도 되는 아이,NEW,2022-07-13,9198000,12932000,1022,1436,4,4

In [4]:
# json 파일로 추출하고 싶다면 실행 
daily_data.to_json('daily_data_{}.json'.format(date_now))



# 엑셀로 저장하고 싶다면 
daily_data.to_excel('daily_data_{}.xlsx'.format(date_now))

### 2) 다양성 영화 한정 순위

In [5]:
key = "b70da09aaa9ad76068d1154144860ac5"
date_now = date.today() - timedelta(1)
date_now = date_now.strftime('%Y%m%d')
multi_yesorno = "Y"
url = 'http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key={}&multiMovieYn={}&targetDt={}'.format(key, multi_yesorno,date_now)

res = requests.get(url)

text = res.text
d = json.loads(text)
movie_list = []

for b in d['boxOfficeResult']['dailyBoxOfficeList']:
    movie_list.append([b['rank'], b['movieNm'], b['rankOldAndNew'], b['openDt'], 
    b['salesAmt'], b['salesAcc'], b['audiCnt'], b['audiAcc'], b['scrnCnt'], b['showCnt']])
    

daily_data = pd.DataFrame(data=movie_list, columns=['순위', '영화명', '신규진입여부', '개봉일자', '당일 매출액', '누적 매출액', '당일 관객수', '누적 관객수', '당일 상영 스크린 수', 
                                            '당일 상영 횟수'])

In [6]:
# 당일(하루 전까지만 가능) 박스오피스 순위(옵션 다양: http://www.kobis.or.kr/kobisopenapi/homepg/apiservice/searchServiceInfo.do)
print('검색 날짜 : {}'.format(date_now))
daily_data

검색 날짜 : 20220711

,순위,영화명,신규진입여부,개봉일자,당일 매출액,누적 매출액,당일 관객수,누적 관객수,당일 상영 스크린 수,당일 상영 횟수
0,1,큐어,OLD,2022-07-06,10393100,132394700,1026,12468,49,83
1,2,컴온 컴온,OLD,2022-06-30,2082700,119255600,209,11952,35,43
2,3,니얼굴,OLD,2022-06-23,1369000,99358300,161,11075,27,36
3,4,검찰측의 죄인,OLD,,739000,13331000,135,1967,5,5
4,5,애프터 양,OLD,2022-06-01,1300500,356055490,130,36879,13,16
5,6,그대가 조국,OLD,2022-05-25,666000,3097882870,127,332268,3,3
6,7,옆자리 괴물군,OLD,,566000,5988870,111,916,5,5
7,8,히비키,OLD,,537000,3043800,102,464,5,5
8,9,모어,OLD,2022-06-23,691300,75826900,71,9045,17,20
9,10,홀리 모터스,OLD,2013-04-04,761700,170973500,70,21730,7,7

In [7]:
# json 파일로 추출하고 싶다면 실행 
daily_data.to_json('daily_data_{}.json'.format(date_now))



# 엑셀로 저장하고 싶다면 
daily_data.to_excel('daily_data_{}.xlsx'.format(date_now))

## 2. 주간 박스오피스 순위

### 1)  다양성 영화, 상업 영화 전부 포함

In [8]:
key = 'c5cf7452f29a492d33ba4edb3b66811f'

date_now = date.today() - timedelta(2)
date_now = date_now.strftime('%Y%m%d')
url = 'http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json?key={}&targetDt={}'.format(key, date_now)

res = requests.get(url)
text = res.text
d = json.loads(text)
movie_list = []


for b in d['boxOfficeResult']['weeklyBoxOfficeList']:
    movie_list.append([b['rank'], b['movieNm'], b['rankOldAndNew'], b['openDt'], 
    b['salesAmt'], b['salesAcc'], b['audiCnt'], b['audiAcc'], b['scrnCnt'], b['showCnt']])
    

week_data = pd.DataFrame(data=movie_list, columns=['순위', '영화명', '신규진입여부', '개봉일자', '당일 매출액', '누적 매출액', '당일 관객수', '누적 관객수', '당일 상영 스크린 수', 
                                            '당일 상영 횟수'])

In [9]:
# 이틀 전 데이터부터 가능 
week_data

,순위,영화명,신규진입여부,개봉일자,당일 매출액,누적 매출액,당일 관객수,누적 관객수,당일 상영 스크린 수,당일 상영 횟수
0,1,토르: 러브 앤 썬더,NEW,2022-07-06,13037537320,19230118410,1184456,1764877,2044,30056
1,2,탑건: 매버릭,OLD,2022-06-22,8544063530,49904277450,804308,4653723,1329,14123
2,3,헤어질 결심,OLD,2022-06-29,2220445400,8926479560,204482,885281,751,4697
3,4,범죄도시 2,OLD,2022-05-18,926286900,130205751140,84814,12588775,526,2436
4,5,마녀(魔女) Part2. The Other One,OLD,2022-06-15,597675850,28595023380,55857,2772674,438,1904
5,6,빅샤크4: 바다공룡 대모험,OLD,2022-07-06,343780020,391232380,36206,42122,455,1590
6,7,큐어,OLD,2022-07-06,61707100,122001600,5699,11442,55,273
7,8,BIFAN2022 부천 초이스: 단편 1,NEW,,20700000,28300000,4140,5660,1,23
8,9,BIFAN2022 부천 초이스: 단편 2,NEW,,18900000,23650000,3780,4730,1,21
9,10,버즈 라이트이어,OLD,2022-06-15,31056790,3476340660,3328,338836,41,123

In [ ]:
# json 파일로 추출하고 싶다면 실행 
week_data.to_json('daily_data_{}.json'.format(date_now))



# 엑셀로 저장하고 싶다면 
week_data.to_excel('daily_data_{}.xlsx'.format(date_now))

### 2) 다양성 영화 한정 순위

In [10]:
key = 'c5cf7452f29a492d33ba4edb3b66811f'

date_now = date.today() - timedelta(2)
date_now = date_now.strftime('%Y%m%d')
multi_yesorno = "Y"
url = 'http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json?key={}&multiMovieYn={}&targetDt={}'.format(key, multi_yesorno,date_now)
res = requests.get(url)
text = res.text
d = json.loads(text)
movie_list = []


for b in d['boxOfficeResult']['weeklyBoxOfficeList']:
    movie_list.append([b['rank'], b['movieNm'], b['rankOldAndNew'], b['openDt'], 
    b['salesAmt'], b['salesAcc'], b['audiCnt'], b['audiAcc'], b['scrnCnt'], b['showCnt']])
    

week_data = pd.DataFrame(data=movie_list, columns=['순위', '영화명', '신규진입여부', '개봉일자', '당일 매출액', '누적 매출액', '당일 관객수', '누적 관객수', '당일 상영 스크린 수', 
                                            '당일 상영 횟수'])

In [11]:
week_data

,순위,영화명,신규진입여부,개봉일자,당일 매출액,누적 매출액,당일 관객수,누적 관객수,당일 상영 스크린 수,당일 상영 횟수
0,1,큐어,OLD,2022-07-06,61707100,122001600,5699,11442,55,273
1,2,그대가 조국,OLD,2022-05-25,21986800,3097216870,2410,332141,20,51
2,3,컴온 컴온,OLD,2022-06-30,16161100,117172900,1514,11743,51,185
3,4,니얼굴,OLD,2022-06-23,10008400,97989300,1081,10914,28,103
4,5,검찰측의 죄인,NEW,,5013000,12592000,953,1832,5,17
5,6,애프터 양,OLD,2022-06-01,9552100,354754990,937,36749,23,71
6,7,벰: 비컴 휴먼,OLD,2022-06-16,2965000,27437000,587,5305,2,8
7,8,옆자리 괴물군,NEW,,2270500,5422870,425,805,5,14
8,9,모어,OLD,2022-06-23,4535500,75135600,422,8974,17,55
9,10,"아치의 노래, 정태춘",OLD,2022-05-18,2943000,301050210,316,31618,6,13

In [ ]:
# json 파일로 추출하고 싶다면 실행 
week_data.to_json('daily_data_{}.json'.format(date_now))



# 엑셀로 저장하고 싶다면 
week_data.to_excel('daily_data_{}.xlsx'.format(date_now))